### ISSUE TITLE
Initial roadmap

### ISSUE THREAD

**Issue by tamasgal** [tamasgal/lubricate#1]
Here is a basic roadmap (work in progress):

- [ ] Template kinds
  Lubricate will provide bootstrapping for different kind of Python related projects
  - [ ] Python package
    - [x] template variables to be replaced in the bootstrapped folder structure (package name, author, mail, license, short description, Git upstream URL)
    - [x] `setup.py` which allows installation via `pip`
    - [ ] sphinx documentation
      - [ ] readthedocs.org support
    - [ ] unit test suite
    - [ ] coverage reports
    - [ ] continuous integration (and delivery)
      - [ ] GitLab (self-hosted) as highest priority due to to affinity to the KM3NeT experiment
      - [ ] GitHub
      - [ ] Travis
  - [ ] Scientific analysis
    - [ ] Methods to get access to the project directories to avoid hardcoded paths
    - [ ] Hooks for automatically invoking virtualenv activation in scripts or modules
      This can be tricky. How can we have control over the Python interpreter if a script is launched via `python script.py` to make sure the virtualenv is used?
- [ ] Documentation of lubricate
  - [ ] Sphinx docs
  - [ ] Screencast
